### PR TITLE
Plans page reloaded

### PR DESCRIPTION
**Pull request by Veri5ied**
Implemented publishers plans page with navbars
**Demo:** https://getviralplans.netlify.app/

**Screenshots updated**
Screenshot (377)
Screenshot (378)
Screenshot (379)
Screenshot (380)

### CODE REVIEW

**Comment by Netacci** [comment]
You didnt use the color king david suggested for the 800 dollar plan he said #F97068 or #D62839

**Comment by Veri5ied** [comment]
> You didnt use the color king david suggested for the 800 dollar plan he said #F97068 or #D62839

Yeah @Netacci Queennette came up with this one last night

**Comment by Netacci** [comment]
Add your top nav menu

**Comment by Netacci** [comment]
Okay but David's own is fine sha, your cards look shrinked on 768

**Comment by Netacci** [comment]
No footer on your page

**Comment by Veri5ied** [comment]
> Add your top nav menu

@Netacci top nav is there... The bg color made it look as if it's not
topnav
and as for shrinking (padding on texts) and, that's the normal bootstrap card-deck bootstrap working...
Expanding will enter the nav section too but I'll see to it.

As for footer, I didn't see any footer for my section

**Comment by Veri5ied** [comment]
Merge conflicts are much so I used a new branch

**Pull request closed without merging**
