### PR TITLE
feat: built the upgrade account page

### PR DESCRIPTION
**Pull request by emekaelo**
- Built the upgrade account page
- This PR adds the upgrade accounts page to the project
- Test link: https://brunoelo.github.io/getviralua/
- screenshots
desktop view
mobile view

### CODE REVIEW

**Comment by Netacci** [comment]
If you are putting a question mark beside cvv number, you have to put a modal that shows what the cvv num is for when a user clicks on question mark

**Comment by Netacci** [comment]
if this is for advertiser, your side nav is wrong, I can see publisher's list and if it is for publisher then what payment are publisher's making?

**Comment by Netacci** [comment]
I think the font sizes are big oo

**Comment by emekaelo** [comment]
> If you are putting a question mark beside cvv number, you have to put a modal that shows what the cvv num is for when a user clicks on question mark

Tooltip feature implemented
commit: https://github.com/Netacci/envatoweb-FE/pull/31/commits/4bef858897e36707cc36759d057f6345845a0c63

**Pull request merged**
